### ISSUE TITLE
Dynamic device list in "Scan Network"

### ISSUE THREAD

**Issue by crazyideas21** [nyu-mlab/iot-inspector-client#139]
@cdnicoll I know that the "Scan Network" feature hasn't been implemented yet, but when you do, can you please show a dynamic list of devices on the [Scan Network screen](https://xd.adobe.com/view/250bfa62-c34a-4356-9cf3-dedf1313c814-7058/screen/8bc16fbe-0998-47b9-8adb-bc47762a1857) (refreshed roughly once every two seconds)?

Per #138, I've edited the mock data script to generate...
* two new devices every 10 seconds, up to 30 devices
* traffic to/from all devices continuously
 
Note the difference in the device list between the [Scan Network](https://xd.adobe.com/view/250bfa62-c34a-4356-9cf3-dedf1313c814-7058/screen/8bc16fbe-0998-47b9-8adb-bc47762a1857) screen and the [Dashboard](https://xd.adobe.com/view/250bfa62-c34a-4356-9cf3-dedf1313c814-7058/screen/5a8b945a-9d7d-4095-87a8-82f8be6716ec) screen is as follows:
* The device list in Scan Network shows all devices on the network, whether the user decides to inspect them (i.e., checking the boxes) or not. SQL equivalent: `SELECT * FROM device_info`
* The device list in the Dashboard shows just inspected devices: `SELECT * FROM device_info WHERE is_inspected = 1`

**Comment by crazyideas21** [comment]
Thanks for the update @cdnicoll!

I do see that...
* the main dashboard shows devices that are being inspected
* the Scan Network screen shows all devices
* toggling on/off devices in the Scan Network screen results in devices being add/removed from the main dashboard

One thing that I'm not yet seeing is the auto refresh of devices. The mock data script generate...

* two new devices every 10 seconds, up to 30 devices
* traffic to/from all devices continuously

... which reflects the actual case where a real user first starts running Inspector. It takes time to discover devices in a real network. Also, devices come and go (e.g., a guest visiting).

In the current UI, I'd have to manually refresh the page to see new devices. It'd be helpful if you could automatically update the device list, both in the main dashboard and in the "Scan Network" screen.

**Comment by cdnicoll** [comment]
Should auto refresh every 30 seconds now

**Comment by crazyideas21** [comment]
Not really. 30 seconds in, and I see a blank screen:

https://www.loom.com/share/6ed0270de1df400a8dc93cfd7fa2a92c

In the above video, I was running generating the fake data from scratch, while testing the UI. After about 30 seconds, the screen went blank, and Chrome showed errors.

Not sure what's going on @cdnicoll

**Comment by cdnicoll** [comment]
@crazyideas21 I pushed a fix for a few other things, but this was adjusted within the latest PR. Can you try it again and let me know?

**Comment by crazyideas21** [comment]
After the page automatically refreshes itself, I'm still seeing a blank screen.

Here's a screenshot after the page automatically refreshes itself, when I'm seeing a blank screen:

<img width="1408" alt="Screen Shot 2022-12-06 at 11 55 53" src="https://user-images.githubusercontent.com/1479070/205974478-b53dce64-790b-40ff-8b97-b0640b807666.png">

After I manually refresh the page again, the page seems fine, as shown below:

<img width="1406" alt="Screen Shot 2022-12-06 at 11 56 12" src="https://user-images.githubusercontent.com/1479070/205974545-72dd77e8-9ce8-4a30-834f-c5746259c8f7.png">

But when the page automatically refreshes, we're back to the blank screen problem.

The left side shows the output of `yarn dev`. I made sure to pull the latest and did `yarn install:all` and `yarn prisma:generate` before running `yarn dev`.

**Comment by crazyideas21** [comment]
I am testing against the latest version in the `cr-dev` branch with the mock data; the same problem persists:

<img width="563" alt="Screen Shot 2022-12-06 at 12 09 20" src="https://user-images.githubusercontent.com/1479070/205977295-6fe98654-3d08-4fd5-822e-3af011c5fcbe.png">

The `yarn dev` output doesn't seem to include any errors:

<img width="654" alt="Screen Shot 2022-12-06 at 12 11 12" src="https://user-images.githubusercontent.com/1479070/205977557-660f855e-e085-40cf-babb-9a5a8c58e7d3.png">


To reproduce the observation above:

1. Pull the latest `cr-dev` branch.
2. Generate mock data with `python3 generate_mock_data.py`.
3. Set up the UI: `yarn install:all`, followed by `yarn prisma:generate`.
4. Run `yarn dev`.

**Comment by crazyideas21** [comment]
Problem fixed. Looks like I have to do `yarn client:build` first before doing `yarn dev` per @cdnicoll

**Comment by crazyideas21** [comment]
I've updated the README per https://github.com/nyu-mlab/iot-inspector-client/commit/2ca874332be80de69f454cf3b83320b00e270a8f /cc: @cdnicoll
